baseURL = "https://samuel-adekunle.software/" 
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
defaultContentLanguage = "en" 
enableEmoji = true # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
languageCode = "en-gb" 
pygmentsCodefences = true 
pygmentsUseClasses = true 
rssLimit = 10 # Maximum number of items in the RSS feed.
theme = "hermit" 
title = "Samuel Adekunle" 

[author]
name = "Samuel Adekunle"

[blackfriday]
hrefTargetBlank = true
nofollowLinks = true
noreferrerLinks = true

[taxonomies]
tag = "tags"

[params]
dateform = "Jan 2, 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"
dateformShort = "Jan 2"

description = "Samuel Adekunle's Website"
images = ["cover.jpg"]
themeColor = "#494f5c"

bgImg = "cover.jpg"
footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
homeSubtitle = "Incoming STEP @ Google · Incoming President @ Imperial Junior Solutions · EIE II @ Imperial College London"

relatedPosts = true # Add a related content section to all single posts page

code_copy_button = true # Turn on/off the code-copy-button for code-fields
[[params.social]]
name = "email"
url = "mailto://me@samuel-adekunle.software"

[[params.social]]

name = "github"
url = "https://github.com/samuel-adekunle"
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/samuel-adekunle/"

[menu]

[[menu.main]]
name = "Posts"
url = "posts/"
weight = 10

[[menu.main]]
name = "About"
url = "about/"
weight = 20
