baseURL = "https://samuel-adekunle.software"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Samuel Adekunle"
theme = "hermit"
# enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
# googleAnalytics = "UA-123-45"
# disqusShortname = "yourdiscussshortname"

[author]
  name = "Samuel Adekunle"

[blackfriday]
  hrefTargetBlank = true
  noreferrerLinks = true
  nofollowLinks = true

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Samuel Adekunle's Website"
  images = ["cover.jpg"]
  themeColor = "#494f5c"

  homeSubtitle = "Web Developer at Imperial Junior Solutions · Electrical and Electronic Engineering · Imperial College London"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  bgImg = "cover.jpg"

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = "https://github.com/username/repository/commit/"
  
  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]

  [[params.social]]
    name = "github"
    url = "https://github.com/SamtheSaint"
  
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/sam-adekunle-2002/"

  [[params.social]]
    name = "email"
    url = "mailto://samueladekunle2002@yahoo.co.uk"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20
